chat_task:
  description: >
    Agent1 will start a conversation by advocating for Charmander as the best starter Pokémon. Agent2 will counter by defending Pikachu. The debate should continue with each agent presenting arguments and counterarguments.
  expected_output: >
    A lively debate where Agent1 and Agent2 argue over whether Charmander or Pikachu is the better starter Pokémon.
  agent: agent1
